### ISSUE TITLE
Issues while fetching/downloading maven dependencies inside engine docker container

### ISSUE THREAD

**Issue by vipuldarkknight** [codeclimate/codeclimate-checkstyle#34]
Hello there,

Thanks for such a good project to help us out with the code review. I was trying to use maven dependencies inside codeclimate-checkstyle but on running the command mvn jxr:jxr it is unable to fetch/download anything from central repository. I have gone through the configuration and i think codeclimate sets --net to none for all the engines that it uses. I guess setting this variables prevents docker container from using any network. Can you please elaborate on this once? Is this variable configurable or by any means can we use networks inside the docker images(engine images) which codeclimate fetches. Is it possible for us to have network access. 

I would be really thankful if you could reply asap, its kind of urgent project which we are working on right now.

**Comment by fede-moya** [comment]
@vipuldarkknight You are correct, engines do not have access to the internet and this is by design and it's currently not configurable. I don't have much options to offer you this time.

**Comment by filipesperandio** [comment]
That's correct, we disable network access by design. The main idea behind it is that CodeClimate plugins cannot be used in harm ways, specially because there are a lot of contributions from the community.
If some of those dependencies are a good fit for the majority of the users, we try to incorporate those as part of the build process and make them available in the docker image, but unfortunately, we don't provide a way to make network configurable.
